
-- Development-only seed. Do not deploy this as production data.
INSERT OR IGNORE INTO tenants(id,company_identifier,name_ar,name_en)
VALUES ('tenant-demo','DEMO','شركة تجريبية','Demo Company');

INSERT OR IGNORE INTO company_settings(tenant_id,settings_json)
VALUES ('tenant-demo','{"language":"ar","timezone":"Asia/Riyadh"}');

INSERT OR IGNORE INTO roles(id,tenant_id,code,name_ar,system_role)
VALUES
('role-demo-admin','tenant-demo','company_admin','مدير الشركة',0),
('role-demo-hr','tenant-demo','hr','الموارد البشرية',0),
('role-demo-manager','tenant-demo','manager','مدير',0),
('role-demo-employee','tenant-demo','employee','موظف',0);

INSERT OR IGNORE INTO role_permissions(role_id,permission_id,scope_type)
SELECT 'role-demo-admin', id, 'COMPANY' FROM permissions;

INSERT OR IGNORE INTO role_permissions(role_id,permission_id,scope_type)
SELECT 'role-demo-hr', id, 'COMPANY' FROM permissions
WHERE code IN (
'dashboard.view','employees.view','employees.create','employees.edit',
'organization.view','transactions.view','transactions.create','transactions.approve',
'transactions.return','transactions.reject','leave.view','leave.create',
'leave.approve','absence.view','absence.manage','advances.view','advances.create',
'deductions.view','deductions.manage','additions.view','additions.manage',
'payroll.view','reports.view','reports.export'
);

-- Password hash is generated by the application setup script.
-- The first local login user is inserted by `scripts/create-dev-user.mjs`.
