name = "hr-enterprise-saas"
main = "src/worker.js"
compatibility_date = "2026-09-22"

[vars]
APP_NAME = "HR Enterprise"

[[d1_databases]]
binding = "DB"
database_name = "hr-enterprise"
database_id = "43d377a3-8ba3-47ed-adf7-03ec0097ff40"
migrations_dir = "migrations"
